"use client";

import { useState } from "react";
import { FileText, Clock, TrendingUp, CheckCircle2, ChevronRight, File, MoreHorizontal, Download, Share2, Code2, Users, DollarSign, PenTool } from "lucide-react";
import { motion } from "framer-motion";

const documents = [
  {
    id: "tech-arch",
    title: "Technical Architecture Core",
    icon: Code2,
    author: "Nexus (CTO Agent)",
    confidence: "98%",
    timeAgo: "10 mins ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          This document defines the high-level system design and technical stack for the Gengen freemium video generation platform. Focus is on high-throughput GPU scaling and cost optimization.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>1. Infrastructure Layer</h2>
        <p>
          We will deploy a containerized architecture using Kubernetes (EKS). Video rendering will be handled by asynchronous worker nodes utilizing NVIDIA A100 GPU clusters. 
        </p>
        <h2>2. Data Pipeline & Storage</h2>
        <p>
          Video assets will be stored in AWS S3 with CDN distribution via CloudFront. User metadata and project state will be maintained in a distributed PostgreSQL cluster.
        </p>
        <div className="my-6 bg-surface-container border-l-4 border-blue-500 rounded-r-lg p-4 flex gap-4">
          <Code2 className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-semibold text-on-surface m-0 mb-1">Queue Optimization</h4>
            <p className="text-sm text-on-surface-variant m-0">To manage the freemium tier effectively, free-tier render jobs will be pushed to a low-priority Redis queue, while premium users get dedicated high-priority lanes.</p>
          </div>
        </div>
        <h2>3. API Gateway</h2>
        <p>
          A scalable GraphQL API will serve as the gateway between the React/Next.js frontend and the underlying microservices.
        </p>
      </>
    )
  },
  {
    id: "social-media",
    title: "Social Media Strategy",
    icon: Users,
    author: "Vanguard (CMO Agent)",
    confidence: "95%",
    timeAgo: "15 mins ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Comprehensive go-to-market and social media growth plan designed to maximize organic reach and convert free users into paid subscribers for the Gengen platform.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>1. Content Pillars</h2>
        <p>
          Our content strategy across TikTok, Instagram Reels, and Twitter will focus on three main pillars:
        </p>
        <ul>
          <li><strong>"Made with Gengen" Showcases:</strong> Highlighting the best user-generated videos.</li>
          <li><strong>Behind the Scenes:</strong> Building in public, showing how our AI models generate content.</li>
          <li><strong>Creator Tutorials:</strong> Quick 30-second guides on maximizing prompt effectiveness.</li>
        </ul>
        <h2>2. Viral Loop Engineering</h2>
        <p>
          Every video exported on the freemium tier will include a subtle "Generated by Gengen.ai" watermark. Users who share their videos directly to TikTok via our API integration will receive 5 bonus render credits.
        </p>
        <div className="my-6 bg-surface-container border-l-4 border-rose-500 rounded-r-lg p-4 flex gap-4">
          <TrendingUp className="w-5 h-5 text-rose-500 shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-semibold text-on-surface m-0 mb-1">Influencer Outreach</h4>
            <p className="text-sm text-on-surface-variant m-0">We have identified 50 mid-tier AI creators on YouTube. We will provide them with Lifetime Premium accounts in exchange for dedicated walkthrough videos.</p>
          </div>
        </div>
      </>
    )
  },
  {
    id: "monetization",
    title: "Freemium Monetization Model",
    icon: DollarSign,
    author: "Ledger (CFO Agent)",
    confidence: "92%",
    timeAgo: "22 mins ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Financial modeling and tier structuring for the Gengen application to ensure sustainable profit margins despite high GPU compute costs.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>1. Tier Breakdown</h2>
        <ul>
          <li><strong>Basic (Free):</strong> 10 standard-definition renders per month. Watermarked. Slow queue.</li>
          <li><strong>Pro ($19/mo):</strong> 100 HD renders. No watermark. Fast lane queue. Commercial rights.</li>
          <li><strong>Studio ($49/mo):</strong> Unlimited HD renders. API access. 4K upscaling.</li>
        </ul>
        <h2>2. Compute Cost Projections</h2>
        <p>
          Estimated cost per SD render is $0.02. At 10 free renders, the maximum cost liability per free user is $0.20/month. A 2% conversion rate to the $19 Pro tier generates an LTV that covers 95 free users.
        </p>
      </>
    )
  },
  {
    id: "q3",
    title: "Q3 Market Entry Plan",
    icon: FileText,
    author: "Atlas & Nexus",
    confidence: "94%",
    timeAgo: "1 hr ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          This document outlines the strategic approach for entering the mid-market enterprise sector by Q3. 
          The analysis was generated autonomously based on real-time market sentiment and technical feasibility.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>1. Executive Summary</h2>
        <p>
          The primary objective is to capture 5% market share in the B2B SaaS analytics space. We must focus heavily on <strong>SOC2 compliance features</strong> and robust <strong>RBAC (Role-Based Access Control)</strong>.
        </p>
        <h2>2. Market Analysis</h2>
        <p>
          Current sentiment analysis indicates a strong shift away from legacy monolithic systems towards agile, microservice-driven analytics platforms.
        </p>
      </>
    )
  },
  {
    id: "brand",
    title: "Brand Voice & Guidelines",
    icon: PenTool,
    author: "Vanguard",
    confidence: "99%",
    timeAgo: "2 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Core identity documentation ensuring cohesive communication across all product, marketing, and support channels.
        </p>
      </>
    )
  },
  {
    id: "seed-pitch",
    title: "Seed Round Pitch Deck Outline",
    icon: FileText,
    author: "Atlas (CEO Agent)",
    confidence: "97%",
    timeAgo: "3 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          A structured narrative for our upcoming $3M seed round raise, highlighting the explosive growth of AI video and our unique freemium distribution moat.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>1. The Problem</h2>
        <p>Current AI video generation tools are either prohibitively expensive for casual users or too complex (requiring local ComfyUI/GPU setups). There is no mid-market accessible layer.</p>
        <h2>2. The Gengen Solution</h2>
        <p>A web-first, hyper-optimized generation pipeline that commoditizes compute enough to offer a viable freemium tier, instantly capturing the top of the funnel.</p>
        <h2>3. Use of Funds</h2>
        <ul>
          <li><strong>60% Compute & Infrastructure:</strong> Pre-purchasing A100/H100 instances to secure bulk pricing and lower unit economics.</li>
          <li><strong>30% R&D:</strong> Fine-tuning our proprietary temporal consistency models.</li>
          <li><strong>10% Go-to-Market:</strong> Creator sponsorships and viral loop bounties.</li>
        </ul>
      </>
    )
  },
  {
    id: "series-a-valuation",
    title: "Series A Valuation & KPI Targets",
    icon: TrendingUp,
    author: "Ledger (CFO Agent)",
    confidence: "91%",
    timeAgo: "4 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Financial milestones required to reach a $50M+ valuation for a Series A raise within 14 months.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Key Metrics Required</h2>
        <ul>
          <li><strong>ARR (Annual Recurring Revenue):</strong> $2.5M run-rate minimum.</li>
          <li><strong>Free-to-Paid Conversion:</strong> Target of 3.5% (industry average for top decile SaaS).</li>
          <li><strong>Net Revenue Retention (NRR):</strong> &gt; 115%, driven by teams upgrading to Studio tiers.</li>
          <li><strong>Gross Margin:</strong> Must stabilize above 65% post-compute costs.</li>
        </ul>
      </>
    )
  },
  {
    id: "b2b-enterprise",
    title: "B2B Enterprise Sales Strategy",
    icon: Users,
    author: "Atlas & Vanguard",
    confidence: "88%",
    timeAgo: "5 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          While the freemium model drives PLG (Product-Led Growth), enterprise accounts will provide the necessary cash flow to subsidize free compute.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Target Audiences</h2>
        <p>Marketing agencies, real estate firms, and e-commerce brands needing bulk video ad variations.</p>
        <h2>Enterprise Features</h2>
        <ul>
          <li>API Access for automated video rendering at scale.</li>
          <li>Custom model fine-tuning on the client's own brand assets.</li>
          <li>Dedicated Account Managers and SLA guarantees.</li>
        </ul>
      </>
    )
  },
  {
    id: "model-finetune",
    title: "AI Model Fine-Tuning Pipeline",
    icon: Code2,
    author: "Nexus (CTO Agent)",
    confidence: "99%",
    timeAgo: "6 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Technical specifications for our proprietary fine-tuning mechanisms that give Gengen its distinct visual edge over open-source foundational models.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Training Strategy</h2>
        <p>We utilize LoRA (Low-Rank Adaptation) networks applied over the base diffusion models to inject specific cinematic styles and character consistency without the cost of full-parameter training.</p>
        <div className="my-6 bg-surface-container border-l-4 border-emerald-500 rounded-r-lg p-4 flex gap-4">
          <Code2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-semibold text-on-surface m-0 mb-1">Compute Efficiency</h4>
            <p className="text-sm text-on-surface-variant m-0">By caching LoRA weights in VRAM, we can switch user styles with only a 120ms latency penalty, allowing massive multi-tenancy on a single GPU.</p>
          </div>
        </div>
      </>
    )
  },
  {
    id: "legal-framework",
    title: "Legal & Copyright Framework",
    icon: FileText,
    author: "Atlas (CEO Agent)",
    confidence: "95%",
    timeAgo: "8 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Navigating the complex landscape of AI-generated content copyright, IP ownership, and DMCA safe harbor provisions.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>User Ownership</h2>
        <p>Paid tier users receive full commercial rights to their generations. Free tier users are granted a CC-BY (Creative Commons Attribution) license, requiring them to credit Gengen.</p>
        <h2>Content Moderation</h2>
        <p>Strict prompt filtering using an LLM-based moderation layer to prevent the generation of NSFW, deepfakes, or copyrighted character IPs (e.g., Disney characters) to minimize liability.</p>
      </>
    )
  },
  {
    id: "cloud-cost",
    title: "Cloud Cost Optimization Plan",
    icon: DollarSign,
    author: "Ledger & Nexus",
    confidence: "96%",
    timeAgo: "10 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          A blueprint for reducing our primary variable cost (GPU compute) by 40% over the next two quarters.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Spot Instances vs Reserved</h2>
        <p>We will shift 70% of free-tier rendering workloads to AWS/GCP Spot Instances, accepting occasional render delays in exchange for an 80% cost reduction. Paid tier rendering will remain on highly available Reserved Instances.</p>
        <h2>Batching Requests</h2>
        <p>Implementing dynamic batching at the inference server level (using TensorRT) to process multiple user prompts simultaneously through the model.</p>
      </>
    )
  },
  {
    id: "competitor-matrix",
    title: "Competitor Feature Matrix",
    icon: TrendingUp,
    author: "Vanguard (CMO Agent)",
    confidence: "93%",
    timeAgo: "12 hrs ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Analysis of key competitors (Runway, Pika, Sora) and our strategic positioning against them.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Positioning</h2>
        <p>While Sora focuses on ultra-high fidelity realism, Gengen will win on <strong>speed, cost, and social-first stylistic templates</strong> (e.g., Anime, 3D Render, Vaporwave).</p>
        <h2>The Gap</h2>
        <p>Competitors lack robust API integrations for developers. By providing a clean REST API, we can become the infrastructure layer for hundreds of smaller AI apps.</p>
      </>
    )
  },
  {
    id: "retention-analysis",
    title: "User Retention & Churn Analysis",
    icon: Users,
    author: "Atlas (CEO Agent)",
    confidence: "89%",
    timeAgo: "1 day ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Early data analysis on why users abandon the platform and strategies to improve D1 and D7 retention.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>The "Blank Canvas" Problem</h2>
        <p>40% of churn happens when a user signs up but doesn't know what to prompt. </p>
        <h2>Solution</h2>
        <p>Implement a "Remix" feed on the homepage. Users can see popular videos and click a single button to copy the exact prompt and settings to generate their own variation.</p>
      </>
    )
  },
  {
    id: "affiliate-program",
    title: "Affiliate & Partner Program",
    icon: DollarSign,
    author: "Vanguard (CMO Agent)",
    confidence: "94%",
    timeAgo: "1 day ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Leveraging performance marketing and affiliate networks to drive high-intent, converting traffic.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Bounty Structure</h2>
        <p>Affiliates will earn a recurring 20% commission for the first 12 months of any Pro or Studio subscription they generate.</p>
        <h2>Tooling</h2>
        <p>We will provide affiliates with pre-generated video creatives, high-converting landing page variants, and a dedicated tracking dashboard via PartnerStack.</p>
      </>
    )
  },
  {
    id: "incident-response",
    title: "Incident Response Playbook",
    icon: Code2,
    author: "Nexus (CTO Agent)",
    confidence: "100%",
    timeAgo: "2 days ago",
    content: (
      <>
        <p className="lead text-lg mb-8">
          Standard operating procedures for critical platform failures, database outages, or API security breaches.
        </p>
        <hr className="border-outline-variant my-8" />
        <h2>Severity 1 Outages</h2>
        <p>If the render queue exceeds a 5-minute wait time for paid users, the system will automatically auto-scale up to 50 additional GPU nodes. If nodes are unavailable, free tier rendering will be paused to prioritize paying customers.</p>
        <h2>Communication Protocol</h2>
        <p>All Sev-1 incidents require immediate notification to the engineering Slack channel and automated updates to the public status page.</p>
      </>
    )
  }
];

export default function StrategyPage() {
  const [activeDocId, setActiveDocId] = useState(documents[0].id);

  const activeDoc = documents.find(d => d.id === activeDocId) || documents[0];

  return (
    <div className="px-6 md:px-12 pb-8 max-w-[1600px] mx-auto h-[calc(100vh-4rem)] flex flex-col pt-8">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-6 flex justify-between items-end shrink-0"
      >
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-on-surface mb-1">Strategy Documents</h2>
          <p className="text-sm text-on-surface-variant/70 max-w-2xl">
            Review business plans, pitch decks, technical architectures, and marketing strategies generated by the AI team.
          </p>
        </div>
        <div className="flex gap-3">
          <button className="bg-surface-container/50 border border-outline-variant/50 text-on-surface px-4 py-2.5 rounded-xl text-sm font-semibold hover:bg-surface-container hover:border-outline-variant transition-all flex items-center gap-2">
            <Share2 className="w-4 h-4" />
            Share
          </button>
          <button className="bg-gradient-to-r from-emerald-500 to-teal-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:shadow-lg hover:shadow-emerald-500/25 transition-all flex items-center gap-2 active:scale-[0.98]">
            <Download className="w-4 h-4" />
            Export PDF
          </button>
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="flex-1 bg-surface/80 backdrop-blur-xl border border-outline-variant/40 rounded-xl flex overflow-hidden shadow-sm"
      >
        
        {/* Document Sidebar */}
        <div className="w-80 border-r border-outline-variant/30 bg-surface-container/20 p-4 flex flex-col overflow-y-auto">
          <div className="mb-4">
            <h4 className="text-[11px] font-bold text-on-surface-variant uppercase tracking-wider mb-3 px-2">Generated Artifacts</h4>
            <div className="flex flex-col gap-1.5">
              {documents.map((doc) => (
                <button 
                  key={doc.id}
                  onClick={() => setActiveDocId(doc.id)}
                  className={`flex items-center gap-3 text-left px-3 py-2.5 rounded-lg border transition-all ${
                    activeDocId === doc.id 
                      ? 'bg-surface-container-highest text-on-surface border-outline-variant shadow-sm' 
                      : 'text-on-surface-variant border-transparent hover:bg-surface-container hover:text-on-surface'
                  }`}
                >
                  <doc.icon className={`w-4 h-4 shrink-0 ${activeDocId === doc.id ? 'text-primary' : ''}`} />
                  <span className="text-sm font-medium line-clamp-1">{doc.title}</span>
                </button>
              ))}
            </div>
          </div>
        </div>
        
        {/* Document Viewer */}
        <div className="flex-1 bg-surface-container-lowest overflow-y-auto flex flex-col relative">
          
          {/* Metadata Bar */}
          <div className="sticky top-0 z-10 bg-surface-container-lowest/80 backdrop-blur-md border-b border-outline-variant/50 px-12 py-4 flex items-center justify-between">
            <div className="flex items-center gap-2 text-xs text-on-surface-variant">
              <span>Home</span>
              <ChevronRight className="w-3 h-3" />
              <span>Strategy</span>
              <ChevronRight className="w-3 h-3" />
              <span className="text-on-surface font-medium truncate max-w-[200px]">{activeDoc.title}</span>
            </div>
            <div className="flex items-center gap-6">
              <div className="flex items-center gap-2 text-xs text-on-surface-variant">
                <Clock className="w-3.5 h-3.5" />
                <span>Generated {activeDoc.timeAgo} by <strong className="text-on-surface font-medium">{activeDoc.author}</strong></span>
              </div>
              <div className="flex items-center gap-2 text-xs text-on-surface-variant">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Confidence <strong className="text-on-surface font-medium">{activeDoc.confidence}</strong></span>
              </div>
              <button className="text-on-surface-variant hover:text-on-surface transition-colors">
                <MoreHorizontal className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Document Content */}
          <div className="px-12 py-10 max-w-4xl mx-auto w-full">
            <h1 className="text-4xl font-bold tracking-tight text-on-surface mb-6">{activeDoc.title}</h1>
            
            <div className="prose prose-invert prose-slate max-w-none prose-p:text-on-surface-variant prose-headings:text-on-surface prose-strong:text-on-surface prose-ul:text-on-surface-variant prose-li:marker:text-primary">
              {activeDoc.content}
            </div>
          </div>

        </div>
      </motion.div>
    </div>
  );
}
